server:
  port: 8082

spring:
  application:
    name: ms_sba
  security.user:
    name: "sba"
    password: "s3cret"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

